### ISSUE TITLE
bug: `azdo config list` does not show current values

### ISSUE THREAD

**Issue by tmeckel** [tmeckel/azdo-cli#33]
When executing `azdo config list` with the following settings in `config.yml`:

```yaml
# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor azdo should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for azdo commands
aliases:
    co: pr checkout
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser azdo should use when opening URLs. If blank, will refer to environment.
browser:
```

The result is empty

```text
git_protocol=
editor=
prompt=
pager=
http_unix_socket=
browser=
default_organization=
```

Same when specifying an organization via `-o`
